---
tasks:
- name: helpers.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/helpers.rb
- name: inspection_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/inspection_steps.rb
- name: managing_requests_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/managing_requests_steps.rb
- name: navigation_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/navigation_steps.rb
- name: periods_and_states_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/periods_and_states_steps.rb
- name: personas_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/personas_steps.rb
- name: placeholders.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/placeholders.rb
- name: procurement_groups_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/procurement_groups_steps.rb
- name: requests_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/requests_steps.rb
- name: roles_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/roles_steps.rb
- name: section_my_requests_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/section_my_requests_steps.rb
- name: templates_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/templates_steps.rb
- name: users_and_organisations_steps.rb
  scripts:
    test:
      body: bundle exec rubocop -c engines/procurement/.rubocop.yml --except Metrics/ModuleLength
        engines/procurement/spec/steps/users_and_organisations_steps.rb
